### ISSUE TITLE
Error during file download occurred on https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

### ISSUE THREAD

**Issue by INHack20** [cravler/CravlerMaxMindGeoIpBundle#22]
The maxmind policies were updated and anonymous downloads are not allowed, is there any way to continue using the bundle with some type of key?

Info here:
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by cravler** [comment]
1. [Sign up for a MaxMind account](https://www.maxmind.com/en/geolite2/signup) (no purchase required)
2. Set your password and create a [license key](https://www.maxmind.com/en/accounts/current/license-key)
    `Will this key be used for GeoIP Update? > No`
3. Edit `config.yaml`

```yaml
parameters:
    max_mind.license_key: "<YOUR_LICENSE_KEY>"

cravler_max_mind_geo_ip:
    source:
        country: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&suffix=tar.gz&license_key=%max_mind.license_key%"
        city: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz&license_key=%max_mind.license_key%"
        asn: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&suffix=tar.gz&license_key=%max_mind.license_key%"
    md5_check:
        country: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&suffix=tar.gz.md5&license_key=%max_mind.license_key%"
        city: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz.md5&license_key=%max_mind.license_key%"
        asn: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&suffix=tar.gz.md5&license_key=%max_mind.license_key%"
```
