### ISSUE TITLE
Bad country

### ISSUE THREAD

**Issue by lbcd** [cravler/CravlerMaxMindGeoIpBundle#4]
Hello,

Thank for your work. I have an issue for some IP.
Ex: 158.255.99.130 
With your bundle this IP is in Austria. But when I try on 
https://www.maxmind.com/fr/geoip-demo
It is in France.

Have you got the same problem? Do you thing I'm doing something wrong?

Thank you.

Louis

**Comment by lbcd** [comment]
Hello,

So I think it database that is not enough up to date. I buy a licence on maxmind but when I add my credential on config it still download free database.

Have you got an idea?

Thank you 

Louis

**Comment by cravler** [comment]
`cravler_max_mind_geo_ip.client` config used for [Web Service Client](https://github.com/maxmind/GeoIP2-php#web-service-client)  and can be used like:

``` php
$geoIpService = $container->get('cravler_max_mind_geo_ip.service.geo_ip_service');
$client = $geoIpService->getClient();
```

if you need full databases, you need specify where download it:

``` yaml
cravler_max_mind_geo_ip:
    source:
        country: 'http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz'
        city: 'http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'
        connection_type: ~
        anonymous_ip: ~
        domain: ~
        isp: ~
```
